# Generated by Django 4.2.7 on 2025-06-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(help_text='Descriptive name for this API key', max_length=100)),
                ('key_prefix', models.CharField(help_text='Public prefix of the API key', max_length=8, unique=True)),
                ('key_hash', models.CharField(help_text='Hashed version of the complete API key', max_length=128)),
                ('permissions', models.JSONField(default=dict, help_text='Permissions for this API key')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.PositiveIntegerField(default=1000, help_text='Requests per hour limit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
