# Generated by Django 4.2.7 on 2025-06-27 19:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='permissions',
            field=models.JSONField(default=dict, help_text='API key permissions (JSON format, max 10KB)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address (max 500 characters)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years (0-150)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Valid email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text="User's full name (letters, spaces, hyphens, apostrophes only)", max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='International phone number format: +1234567890', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (JPG, PNG, GIF, WebP - max 5MB, 2048x2048px)', null=True, upload_to=users.models.user_profile_picture_path),
        ),
    ]
